{{- $config :=  yamlFile "../../config.yml" -}}
{{- $qaWebHostname := joindomain $config.qa.web.publicHostname.subdomain (ternary "localhost" $config.qa.web.publicHostname.domain (eq $config.routing "local")) -}}
variablePrefix: "$"
http:
    internalAddress: "[::]:80"

db:
    url: mongodb://root:$MONGO_INITDB_ROOT_PASSWORD@qadb.localhost:{{ $config.qa.db.port }}
dev:
    insecureSkipInterossea: false
    importOldMeetings: false

mail:
    username: {{ $config.interossea.server.mail.username}}
    password: $MAIL_PASSWORD
    smtpServer: {{ $config.interossea.server.mail.smtpServer}}
    fromName: Queer Augsburg
    fromAddress: {{ $config.interossea.server.mail.fromAddress}}
    userAgent: {{ $config.interossea.server.mail.userAgent}}
    replyTo: {{ $config.interossea.server.mail.replyTo}}

services:
    - id: qa
      allowedOrigins: [{{ ternary "https://" "http://" $config.tls true }}{{ $qaWebHostname}}]

serviceId: qa

interossea:
    url: http://$INTEROSSEA_INTERNAL_URL
    assertionValiditySeconds: 600

uiOrigin: {{ ternary "https://" "http://" $config.tls true }}{{ $qaWebHostname}}
