variablePrefix: "$"
http:
    internalAddress: "[::]:8080"
db:
    url: mongodb://root:root@localhost:27017
dev:
    insecureSkipInterossea: true
    importOldMeetings: false

services:
    - id: qa
      allowedOrigins: [http://localhost:5173]

serviceId: qa

interossea:
    url: http://$INTEROSSEA_INTERNAL_URL
    assertionValiditySeconds: 600

uiOrigin: http://localhost:5173
