// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Address { street: string, number: string, addition: string | null, zip: string, city: string, country: string, }