// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommonMeetingTag = "Kultur" | "Party" | "Orga" | "Sport" | "Education" | "Meet" | "Students" | "Marketing" | "Cinema" | "Talks" | "Open" | "Explores" | "Connect" | "Ostqueer" | "Queermas";