// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface ConfirmSendEmailRequestBody { preview_id: string, verification_code: string, testing_mode: boolean | null, }