// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommonMeetingTag } from "./CommonMeetingTag";
import type { QueerMeetingTag } from "./QueerMeetingTag";

export interface MeetingTags { freeform: Array<string>, common: Array<CommonMeetingTag>, queer: Array<QueerMeetingTag>, }