// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MeetingLocation } from "./MeetingLocation";
import type { MeetingStatus } from "./MeetingStatus";
import type { MeetingTags } from "./MeetingTags";

export interface Meeting { _id: string, title: string, authority: string, age_restriction: Array<number>, time: bigint | null, location: MeetingLocation, description: string, price: Array<number>, trigger_warning: string | null, attendance: number | null, rating: number | null, tags: MeetingTags, status: MeetingStatus, }