// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { MemberType } from "./MemberType";

export interface Member { type: MemberType, legal_person: boolean, first_name: string | null, last_name: string | null, institution: string | null, pronouns: string | null, address: Address, email: string, phone: string | null, start_data: bigint, end_date: bigint | null, approved: boolean, }