// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type QueerMeetingTag = "Everyone" | "Queer" | "Gay" | "Lesbian" | "Trans" | "Bi" | "Asexual" | "Aromantic" | "Inter" | "Poly";