// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EmailAttachment } from "./EmailAttachment";

export interface SendEmailPreviewRequestBody { subject: string, body: string, attachments: Array<EmailAttachment>, reply_to: string | null, }