// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface SendEmailPreviewResponseBody { preview_id: string, recipient_count: number, }