// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SubmittedMember } from "./SubmittedMember";

export interface SetOwnMemberDataRequestBody { member: SubmittedMember, }