// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Address } from "./Address";
import type { MemberType } from "./MemberType";
import type { Name } from "./Name";

export interface SubmittedMember { type: MemberType, natural_person: boolean, name: Name | null, institution: string | null, pronouns: string | null, address: Address, email: string, phone: string | null, user_notes: string | null, reference: string | null, approved_charter: boolean, approved_privacy: boolean, above_18: boolean, }