// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MembershipStatus } from "./MembershipStatus";

export interface UpdateMemberStatusRequestBody { user_id: string, new_status: MembershipStatus, send_mail: boolean, update_reason: string | null, }