// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InternalMember } from "./InternalMember";
import type { UserCapabilities } from "./UserCapabilities";

export interface User { _id: string, member: InternalMember | null, admin: boolean, capabilities: Array<UserCapabilities> | null, }