// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Member } from "./Member";

export interface User { _id: string, member: Member | null, admin: boolean, }