// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InternalMember } from "./InternalMember";

export interface User { _id: string, member: InternalMember | null, admin: boolean, }