dev: true

reverseProxy:
    create: true
    network: rp

tls: false

routing: local

backup:
    create: true
    schedule: "@every 30s" #"@weekly"

internal:
    mattermost:
        enabled: true
        domain: queer-augsburg.de
        subdomain: mm

qa:
    web:
        build:
            enabled: true
            path: ../../web/
            dockerfile: Dockerfile
        publicHostname:
            domain: queer-augsburg.de
            subdomain: web
    server:
        build:
            enabled: true
            path: ../../server/
            dockerfile: Dockerfile
        publicHostname:
            domain: queer-augsburg.de
            subdomain: api
    db:
        exposeToLocalhost: true
        port: 27018

interossea:
    server:
        allowNewUsers: true
        createUsers: [mail@queer-augsburg.de, test@vindelicum.eu]
        makeUsersAdmin: [mail@queer-augsburg.de, test@vindelicum.eu]
        create: true
        internalHostname: qa-interossea-server
        publicHostname:
            domain: queer-augsburg.de
            subdomain: accounts-server
        build:
            enabled: true
            path: /home/paul/Documents/interossea/server/
            dockerfile: Dockerfile
        mail:
            username: no-reply@queer-augsburg.de
            smtpServer: mx.vindelicum.eu
            fromName: Queer Augsburg
            fromAddress: no-reply@queer-augsburg.de
            userAgent: Sugar-Free-Mail-2023
            replyTo: mail@queer-augsburg.de
        db:
            exposeToLocalhost: true
            port: 27019
    web:
        displayNav: false
        create: true
        publicHostname:
            domain: queer-augsburg.de
            subdomain: accounts
        build:
            enabled: true
            path: /home/paul/Documents/interossea/web/
            dockerfile: Dockerfile
